language: haskell

before_install:
  - git submodule update --init --recursive

branches:
  only:
    - master

install:
  - cabal update && cabal install Cabal cabal-install && cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests && cabal build && cabal test
